[workspace]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
name = "0729-InterviewQuestions"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
jlab = "jupyter lab question-python-engineering.ipynb"
solution_1 = 'python .\solutions\1.py'
solution_1_diagonal = 'python .\solutions\1_diagonal.py'
solution_1_stud_wall = 'python .\solutions\1_stud_wall.py'
solution_3 = 'python .\solutions\3.py'
solution_2 = 'python .\solutions\2.py'

[dependencies]
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.3,<4"
jupyterlab = ">=4.4.5,<5"
fluids = ">=1.1.0,<2"
